config/routes.rb
Rails.application.routes.draw do
  filter :locale

  scope "(:locale)", locale: /#{I18n.available_locales.join("|")}/ do
    resources :costs do
      collection do
        post 'order'
        get 'range'             
      end

    get '*path', to: redirect("/#{I18n.default_locale}/%{path}")
    post '*path', to: redirect("/#{I18n.default_locale}/%{path}")
    end

    resources :incomes
    resources :categories

end

   root 'costs#index'

end

app/models/cost.rb
class Cost < ActiveRecord::Base
	belongs_to :category
	validates :amount, presence: true
	validates :category_id, presence: true
	validates :spent_on, presence: true	
end

app/controllers/costs_controller.rb
class CostsController < ApplicationController
  before_action :set_cost, only: [:show, :edit, :update, :destroy]

  # GET /costs
  # GET /costs.json
  def index
   @costs = Cost.all
   @costs_order = Cost.order(spent_on: :asc)
   #@costs_sum = Cost.select("category_id, sum(amount) as total_amount").group("category_id")
  #@costs_sum = Cost.sum(:amount)
    @costs_sum = Cost.group(:category_id).sum(:amount)
    date1 = Date.parse('august 1 2015')
    date2 = Date.parse('august 10 2015')
    @cost_daterange = Cost.where(:spent_on => date1..date2)
    @costs_sum_daterange = @cost_daterange.group(:category_id).sum(:amount)
    @costs_total = Cost.sum(:amount)
    if @costs_total >= (0.9) * Income.sum(:amount) 
      flash.now[:alert] = "Spent 90% of your income"
      flash[:alert] = "Spent 90% of your income"
    end
    @incomes_total = Income.sum(:amount)
   @costs_sum_daterange_join = Cost.joins(:category).order(spent_on: :asc)

   #@costs_sum_daterange_join = Cost.all(:all, :joins => :category)

  end

  # GET /costs/1
  # GET /costs/1.json
  def show
  end

  # GET /costs/new
  def new
    @cost = Cost.new
  end

  def there
     
   end

  # GET /costs/1/edit
  def edit
  end

  def range

  end

  def order
  date1 = params[:date1] 
  date2 = params[:date2]
    #@date1 = Date.parse('august 1 2015')
    #@date2 = Date.parse('august 10 2015')
    #@costs_daterange = Cost.find(:all, :conditions => ['spent_on >= ? and spent_on <= ?', params[:start_date], params[:end_date]])
   @cost_daterange = Cost.all.where(:spent_on => date1..date2)
   @costs_sum_daterange = @cost_daterange.group(:category_id).sum(:amount)

   respond_to do |format|
  #format.html { redirect_to @cost, notice: date2 }       
    format.html { render :order, notice: 'Cost was successfully created.'}
             end
  end

  # POST /costs
  # POST /costs.json
  def create
    @cost = Cost.new(cost_params)
    respond_to do |format|
      if @cost.save
        @costs_total = Cost.sum(:amount)
        if @costs_total >= (0.9) * Income.sum(:amount)
          flash[:alert] = "Spent 90% of your income"
          flash.now[:alert] = "Spent 90% of your income"
        end
      #date1 = params[:date1] 
        format.html { redirect_to @cost , alert: "ALERT!!  Spent 90% of your income", notice: 'Cost was successfully created.'  }
        format.json { render :show, status: :created, location: @cost }
      else
        format.html { render :new }
        format.json { render json: @cost.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /costs/1
  # PATCH/PUT /costs/1.json
  def update
    respond_to do |format|
      if @cost.update(cost_params)
        format.html { redirect_to @cost, notice: 'Cost was successfully updated.' }
        format.json { render :show, status: :ok, location: @cost }
      else
        format.html { render :edit }
        format.json { render json: @cost.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /costs/1
  # DELETE /costs/1.json
  def destroy
    @cost.destroy
    respond_to do |format|
      format.html { redirect_to costs_url, notice: 'Cost was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

skip_before_filter :verify_authenticity_token
  
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cost
      @cost = Cost.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cost_params
      params.require(:cost).permit(:amount, :category_id, :spent_on)
    end
end

app/helpers/costs_helper.rb
module CostsHelper
end

app/views/costs/_form.html.erb
<%= form_for(@cost) do |f| %>
  <% if @cost.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@cost.errors.count, "error") %> prohibited this cost from being saved:</h2>

      <ul>
      <% @cost.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :amount %>&nbsp;&nbsp;
    <%= f.number_field :amount %>
  </div>
  <br/>
  <div class="field">
    <%= f.label :category_id %>&nbsp;&nbsp;
    <%= f.select(:category_id, options_for_select([['1-Salary', 1 ],['2-Property',2],['3-Business',3], ['4-Freelancing',4], ['5-Housing',5], ['6-Transportation',6], ['7-Food',7], ['8-Shopping',8], ['9-Entertainment',9]])) %>
  </div>
<br />
  <div class="field">
    <%= f.label :spent_on %>&nbsp;&nbsp;    
    <%= f.date_select :spent_on%>
   
 </div>

<br />
    <% if flash.now[:alert]%>
    <div class="actions">
      <%= f.submit :onclick => "alert('Spending exceeds 90% of the income')" %></div>
    </div>
    <% else %>
      <div class="actions">
      <%= f.submit %></div>
    </div>
    <% end %>

  <% end %>

app/views/costs/_form2.html.erb
<%= form_for(start_date,end_date) do |f| %>

  <div class="field">
    <%= f.date_select :dateinstructed, :order => [:day, :month, :year] %>
  </div>
  <div class="field">
    <%= f.date_select :dateinstructed, :order => [:day, :month, :year] %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>

<% end %>

app/views/costs/edit.html.erb
<h1>Editing Cost</h1>

<%= render 'form' %>

<%= link_to 'Show', @cost %> |
<%= link_to 'Back', costs_path %>

app/views/costs/index.html.erb
<p id="notice"><%= notice %></p>


<div class ="center_top"><h3 id = "center_top_1"><%= t "costs.total"%>: <%= @costs_total%></h3>

<h3 id = "center_top_2"> <%= t "incomes_total"%>: <%= @incomes_total%></h3></div>

<% if flash.now[:alert] %>
    <div class="alert"><%= flash.now[:alert] %>
  <% end %></div>

<br />
  <div class ="center_costs"><%= link_to t('.new_cost'), new_cost_path %>
<%= link_to t('.date_range'), range_costs_path %>

<h1><%= t "costs.title"%></h1></div>

<table class = "TFtable" cellpadding ="10" bgcolor = "#FFFFCC">
  <thead>
    <tr>
      <th><%= Cost.human_attribute_name(:amount)%></th>
      <th><%= Cost.human_attribute_name(:category_id)%></th>
      <th><%= Cost.human_attribute_name(:spent_on)%></th>
      <th><%= Cost.human_attribute_name(:category)%></th>
    </tr>
  </thead>
  <tbody>
    <% @costs_sum_daterange_join.each do |cost| %>
      <tr>
        <td><%= cost.amount %></td>
        <td><%= cost.category_id %></td>
        <td><%= cost.spent_on %></td>
        <td><%= cost.category.name%></td>
        <td><%= link_to t('.show') , cost %></td>
        <td><%= link_to t('.edit') , edit_cost_path(cost) %></td>
        <td><%= link_to t('.destroy') , cost, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br />

app/views/costs/new.html.erb
<div class = "new_costs"><h1 id="new_cost_title"><%= t "new.title"%></h1>
	<br />

<%= render 'form' %></div>

<div id = "new_cost_back"><%= link_to t('.back'), costs_path %></div>

app/views/costs/order.html.erb
<h1>Listing Ordered Costs</h1>

<table>
  <thead>
    <tr>
      <th>Category</th>
      <th>Total Amount</th>
    </tr>
  </thead>
  <tbody>
    <% @costs_sum_daterange.each do |key,value| %>
      <tr>
        <td><%= key %></td>
        <td><%= value %></td>
      </tr>
    <% end %>
  </tbody>
</table>


<%= link_to 'Back', costs_path %>

app/views/costs/range.html.erb
<br />
<br />

<div class = "range_center"><h1><%= t "range.title"%></h1>

<form action="order" method="post">

<input type="date" name="date1"/>
<input type="date" name="date2"/>
&nbsp;&nbsp;&nbsp;&nbsp;
<input type="submit"/>

</form></div>

<br />

<div class = "range_links"><%= link_to 'Back', costs_path %>
<%= link_to 'New Cost', new_cost_path %>
<%= link_to 'Order', order_costs_path %></div>

app/views/costs/show.html.erb
<p id="notice"><%= t ".notice" %></p>
<% if flash[:alert] %>
    <div class="alert"><%= flash[:alert]%></div>
  <% end %>


<p>
  <strong><%= Cost.human_attribute_name(:amount)%></strong>
  <%= @cost.amount %>
</p>

<p>
  <strong><%= Cost.human_attribute_name(:category_id)%></strong>
  <%= @cost.category_id %>
</p>

<p>
  <strong><%= Cost.human_attribute_name(:spent_on)%></strong>
  <%= @cost.spent_on %>
</p>

<%= link_to t('.edit'), edit_cost_path(@cost) %> |
<%= link_to t('.back'), costs_path %>