config/routes.rb
Rails.application.routes.draw do
  filter :locale

  scope "(:locale)", locale: /#{I18n.available_locales.join("|")}/ do
    resources :costs do
      collection do
        post 'order'
        get 'range'             
      end

    get '*path', to: redirect("/#{I18n.default_locale}/%{path}")
    post '*path', to: redirect("/#{I18n.default_locale}/%{path}")
    end

    resources :incomes
    resources :categories

end

   root 'costs#index'

end

app/models/income.rb
class Income < ActiveRecord::Base
	belongs_to :category
	validates :amount, presence: true
	validates :category_id, presence: true
	validates :earned_on, presence: true
end

app/controllers/incomes_controller.rb
class IncomesController < ApplicationController
  before_action :set_income, only: [:show, :edit, :update, :destroy]

  # GET /incomes
  # GET /incomes.json
  def index
    @incomes = Income.all
    @incomes_total = Income.sum(:amount)
    @incomes_sum_daterange_join = Income.joins(:category).order(earned_on: :asc)
  end

  # GET /incomes/1
  # GET /incomes/1.json
  def show
  end

  # GET /incomes/new
  def new
    @income = Income.new
  end

  # GET /incomes/1/edit
  def edit
  end

  # POST /incomes
  # POST /incomes.json
  def create
    @income = Income.new(income_params)

    respond_to do |format|
      if @income.save
        format.html { redirect_to @income, notice: 'Income was successfully created.' }
        format.json { render :show, status: :created, location: @income }
      else
        format.html { render :new }
        format.json { render json: @income.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /incomes/1
  # PATCH/PUT /incomes/1.json
  def update
    respond_to do |format|
      if @income.update(income_params)
        format.html { redirect_to @income, notice: 'Income was successfully updated.' }
        format.json { render :show, status: :ok, location: @income }
      else
        format.html { render :edit }
        format.json { render json: @income.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /incomes/1
  # DELETE /incomes/1.json
  def destroy
    @income.destroy
    respond_to do |format|
      format.html { redirect_to incomes_url, notice: 'Income was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_income
      @income = Income.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def income_params
      params.require(:income).permit(:amount, :category_id, :earned_on)
    end
end

app/helpers/incomes_helper.rb
module IncomesHelper
end

app/views/incomes/_form.html.erb
<%= form_for(@income) do |f| %>
  <% if @income.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@income.errors.count, "error") %> prohibited this income from being saved:</h2>

      <ul>
      <% @income.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :amount %><br>
    <%= f.number_field :amount %>
  </div>
  <div class="field">
    <%= f.label :category_id %><br>
    <%= f.number_field :category_id %>
  </div>
  <div class="field">
    <%= f.label :earned_on %><br>
    <%= f.date_select :earned_on %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/incomes/edit.html.erb
<h1>Editing Income</h1>

<%= render 'form' %>

<%= link_to 'Show', @income %> |
<%= link_to 'Back', incomes_path %>

app/views/incomes/index.html.erb
<p id="notice"><%= notice %></p>

<h1><%= t "incomes.title"%></h1>

<table>
  <thead>
    <tr>
      <th><%= Cost.human_attribute_name(:amount)%></th>
      <th><%= Cost.human_attribute_name(:category_id)%></th>
      <th><%= Cost.human_attribute_name(:spent_on)%></th>
      <th><%= Cost.human_attribute_name(:category)%></th>
    </tr>
  </thead>

  <tbody>
    <% @incomes_sum_daterange_join.each do |income| %>
      <tr>
        <td><%= income.amount %></td>
        <td><%= income.category_id %></td>
        <td><%= income.earned_on %></td>
        <td><%= income.category.name%></td>
        <td><%= link_to t('.show'), income %></td>
        <td><%= link_to t('.edit'), edit_income_path(income) %></td>
        <td><%= link_to t('.destroy'), income, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<p><%= t "incomes.total"%>: <%= @incomes_total%></p>

<%= link_to t('.new_income'), new_income_path %>

app/views/incomes/new.html.erb
<div class = "new_incomes"><h1>New Income</h1>

<%= render 'form' %>

<%= link_to 'Back', incomes_path %></div>

app/views/incomes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Amount:</strong>
  <%= @income.amount %>
</p>

<p>
  <strong>Category:</strong>
  <%= @income.category_id %>
</p>

<p>
  <strong>Earned on:</strong>
  <%= @income.earned_on %>
</p>

<%= link_to 'Edit', edit_income_path(@income) %> |
<%= link_to 'Back', incomes_path %>